# Generated by Django 3.0.3 on 2020-06-03 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.CharField(default='20XX', max_length=10)),
                ('sem', models.CharField(default='Default Semester', max_length=30)),
                ('code', models.CharField(default='SUB-CODE', max_length=10)),
                ('slot', models.CharField(default='EX+EX', max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data', models.TextField()),
                ('prev_hash', models.CharField(max_length=500)),
                ('block_hash', models.CharField(max_length=500)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Chain')),
            ],
        ),
    ]
