# Generated by Django 3.0.3 on 2020-06-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='strength',
            field=models.CharField(default=60, max_length=10),
        ),
    ]
