# Generated by Django 3.0.3 on 2020-06-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_chain_strength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='index',
            field=models.IntegerField(null=True),
        ),
    ]
