# Generated by Django 3.0.3 on 2020-06-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20200603_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='strength',
            field=models.CharField(max_length=10),
        ),
    ]
