# Generated by Django 3.0.3 on 2020-06-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20200603_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='chain',
            name='sem',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='chain',
            name='slot',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='chain',
            name='strength',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chain',
            name='year',
            field=models.IntegerField(),
        ),
    ]
